// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart';
import 'firebase_options.dart';
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBxYGJzGptf0Kuu4Ren1HyEBb3AuxO3aYY',
    appId: '1:437069537567:web:3695b21d1027a2a5bf502a',
    messagingSenderId: '437069537567',
    projectId: 'catatan-matkul-2327240030',
    authDomain: 'catatan-matkul-2327240030.firebaseapp.com',
    databaseURL:
        'https://catatan-matkul-2327240030-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'catatan-matkul-2327240030.firebasestorage.app',
    measurementId: 'G-8WQ0VZ6WWB',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4NniOL_1SNH_pQnJwkZdW0Ib6EfW64Hc',
    appId: '1:437069537567:ios:332e202d2d4d096cbf502a',
    messagingSenderId: '437069537567',
    projectId: 'catatan-matkul-2327240030',
    databaseURL:
        'https://catatan-matkul-2327240030-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'catatan-matkul-2327240030.firebasestorage.app',
    iosBundleId: 'com.example.catatanKuliah2327240030',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA4NniOL_1SNH_pQnJwkZdW0Ib6EfW64Hc',
    appId: '1:437069537567:ios:332e202d2d4d096cbf502a',
    messagingSenderId: '437069537567',
    projectId: 'catatan-matkul-2327240030',
    databaseURL:
        'https://catatan-matkul-2327240030-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'catatan-matkul-2327240030.firebasestorage.app',
    iosBundleId: 'com.example.catatanKuliah2327240030',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBxYGJzGptf0Kuu4Ren1HyEBb3AuxO3aYY',
    appId: '1:437069537567:web:ee11af974be98610bf502a',
    messagingSenderId: '437069537567',
    projectId: 'catatan-matkul-2327240030',
    authDomain: 'catatan-matkul-2327240030.firebaseapp.com',
    databaseURL:
        'https://catatan-matkul-2327240030-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'catatan-matkul-2327240030.firebasestorage.app',
    measurementId: 'G-GBLN1EXB1Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYI6P5mcTvsf9nNCf2GKr7Jg69-utCM14',
    appId: '1:437069537567:android:bb8f23957fc992c9bf502a',
    messagingSenderId: '437069537567',
    projectId: 'catatan-matkul-2327240030',
    databaseURL:
        'https://catatan-matkul-2327240030-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'catatan-matkul-2327240030.firebasestorage.app',
  );
}
